<?php
$skin_path = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);
$skin_path .= 'frontend/base/default/toweringmedia/agepopup/';
?>
<link href="<?php echo $skin_path?>tmpopup.css" rel="stylesheet" />
<script type="text/javascript">
if (typeof jQuery == 'undefined') {
    var script = document.createElement('script');
    script.type = "text/javascript";
    script.src = "http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js";
    document.getElementsByTagName('head')[0].appendChild(script);
}
</script>
